name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Check Node & NPM versions
        run: |
          echo -e "\\033[1;36mnode --version\\033[0;02m"
          node --version

          echo -e "\\033[1;36mnpm --version\\033[0;02m"
          npm --version

      - name: Build
        run: |
          npm install
          npm run prod

      - name: Deploy
        run: |
          echo -e "\\033[1;36mgit commit -am commit before checkout\\033[0;02m"
          git commit -am "commit before checkout"

          echo -e "\\033[1;36mgit checkout gh-pages\\033[0;02m"
          git checkout gh-pages

          echo -e "\\033[1;36mrm index* main* polyfills* runtime* styles*\\033[0;02m"
          rm -f index* main* polyfills* runtime* styles*

          echo -e "\\033[1;36mcp dist/index* .\\033[0;02m"
          cp dist/index* .

          echo -e "\\033[1;36mcp dist/main* .\\033[0;02m"
          cp dist/main* .

          echo -e "\\033[1;36mcp dist/polyfills* .\\033[0;02m"
          cp dist/polyfills* .

          echo -e "\\033[1;36mcp dist/runtime* .\\033[0;02m"
          cp dist/runtime* .

          echo -e "\\033[1;36mcp dist/styles* .\\033[0;02m"
          cp dist/styles* .

          echo -e "\\033[1;36msed -i 's:src=":src="ahenteti-todos/:g' index.html\\033[0;02m"
          sed -i 's:src=":src="ahenteti-todos/:g' index.html

          echo -e "\\033[1;36msed -i 's:href="favicon:href="ahenteti-todos/favicon:g' index.html\\033[0;02m"
          sed -i 's:href="favicon:href="ahenteti-todos/favicon:g' index.html

          echo -e "\\033[1;36msed -i 's:href="styles:href="ahenteti-todos/styles:g' index.html\\033[0;02m"
          sed -i 's:href="styles:href="ahenteti-todos/styles:g' index.html

          echo -e "\\033[1;36mgit config user.name ahenteti\\033[0;02m"
          git config user.name ahenteti

          echo -e "\\033[1;36mgit config user.email ahmad.henteti@gmail.com\\033[0;02m"
          git config user.email ahmad.henteti@gmail.com

          echo -e "\\033[1;36mgit remote set-url origin https://*****@github.com/ahenteti-todos\\033[0;02m"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_TO_GH_PAGES }}@github.com/ahenteti/ahenteti-todos.git

          echo -e "\\033[1;36mgit add .\\033[0;02m"
          git add .

          echo -e "\\033[1;36mgit commit -am new website version\\033[0;02m"
          git commit -m "new website version"

          echo -e "\\033[1;36mgit push\\033[0;02m"
          git push
